steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["rm", "gs://desarrollos.mudafy.com/**"]
  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        "cp",
        "-r",
        "-c",
        "-z",
        "css,js,map,html,htm",
        "./",
        "gs://desarrollos.mudafy.com",
      ]

